enum ConfigKey {
  JWT_SECRET_ACCESS_TOKEN_KEY = 'JWT_SECRET_ACCESS_TOKEN_KEY',
  JWT_SECRET_REFRESH_TOKEN_KEY = 'JWT_SECRET_REFRESH_TOKEN_KEY',
  TOKEN_EXPIRED_IN = 'TOKEN_EXPIRED_IN',
  REFRESH_TOKEN_EXPIRED_IN = 'REFRESH_TOKEN_EXPIRED_IN',
}

export default ConfigKey;
